import {Platform, StatusBar, StyleSheet} from 'react-native';
import {colors} from './theme';

export const styles = StyleSheet.create({
  fill: {flex: 1},
  appSafe: {flex: 1, backgroundColor: colors.background},
  mainContent: {flex: 1},
  splash: {flex: 1, backgroundColor: colors.backgroundDeep},
  splashShade: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0, 8, 15, .12)'},
  splashContent: {...StyleSheet.absoluteFillObject, alignItems: 'center'},
  splashHeadingPanel: {
    position: 'absolute',
    top: '9.85%',
    width: '100%',
    height: '29.4%',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,.42)',
  },
  splashLogo: {position: 'absolute', top: '40.5%', width: 173, height: 201, resizeMode: 'contain'},
  splashTitle: {color: colors.white, fontSize: 35, lineHeight: 40, fontWeight: '700', letterSpacing: -0.6, textAlign: 'center'},
  splashSubtitle: {color: colors.white, fontSize: 16, lineHeight: 21, fontStyle: 'italic', marginTop: 18},
  splashLoader: {position: 'absolute', bottom: '10.3%', width: 42, height: 42, overflow: 'hidden'},
  splashWebView: {flex: 1, backgroundColor: 'transparent'},
  splashWebViewContainer: {backgroundColor: 'transparent'},
  brandRow: {flexDirection: 'row', alignItems: 'center'},
  brandLogo: {width: 44, height: 52, resizeMode: 'contain', marginRight: 10},
  brandLogoSmall: {width: 29, height: 34, resizeMode: 'contain', marginRight: 7},
  brandName: {color: colors.white, fontSize: 18, fontWeight: '700'},
  brandSub: {color: colors.muted, fontSize: 8, fontWeight: '700', letterSpacing: 2},
  brandNameSmall: {color: colors.white, fontSize: 13, fontWeight: '700'},
  brandSubSmall: {color: colors.muted, fontSize: 6, fontWeight: '700', letterSpacing: 1.5},
  onboardingImage: {flex: 1, backgroundColor: colors.backgroundDeep},
  onboardingShade: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(3,8,12,.37)', borderWidth: 4, borderColor: colors.backgroundDeep},
  onboardingTop: {paddingHorizontal: 24, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  skip: {color: colors.white, fontSize: 11, fontWeight: '700', letterSpacing: 1.4},
  onboardingCopy: {marginTop: 'auto', paddingHorizontal: 24, paddingBottom: 26, paddingTop: 85, backgroundColor: 'rgba(5,10,14,.58)'},
  onboardingCopyCompact: {paddingTop: 28, paddingBottom: 16},
  eyebrow: {color: colors.red, fontSize: 9, fontWeight: '800', letterSpacing: 1.7, marginBottom: 12},
  onboardingTitle: {color: colors.white, fontSize: 40, lineHeight: 43, fontWeight: '700', letterSpacing: -1.4},
  onboardingTitleCompact: {fontSize: 32, lineHeight: 35},
  onboardingText: {color: '#CDD3D7', fontSize: 14, lineHeight: 21, marginTop: 14, maxWidth: 330},
  onboardingFooter: {marginTop: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  dots: {flexDirection: 'row', gap: 7},
  dot: {width: 5, height: 5, borderRadius: 3, backgroundColor: 'rgba(255,255,255,.35)'},
  dotActive: {width: 24, backgroundColor: colors.red},
  primaryButton: {height: 48, minWidth: 132, backgroundColor: colors.red, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20},
  fullButton: {height: 52, backgroundColor: colors.red, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20, marginTop: 20},
  buttonPressed: {opacity: 0.78},
  primaryButtonText: {color: colors.white, fontSize: 11, fontWeight: '800', letterSpacing: 1.3},
  buttonArrow: {color: colors.white, fontSize: 20, marginTop: -2},
  header: {height: 62, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  headerTitle: {color: colors.white, fontSize: 16, fontWeight: '700'},
  avatar: {width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, alignItems: 'center', justifyContent: 'center'},
  avatarText: {color: colors.white, fontSize: 12, fontWeight: '700'},
  homeScroll: {paddingHorizontal: 20, paddingBottom: 35},
  homeKicker: {color: colors.red, fontSize: 9, fontWeight: '800', letterSpacing: 1.8, marginTop: 22},
  homeGreeting: {color: colors.white, fontSize: 32, lineHeight: 38, fontWeight: '700', letterSpacing: -1, marginTop: 7},
  homeLead: {color: colors.muted, fontSize: 13, lineHeight: 20, maxWidth: 330, marginTop: 8},
  heroCard: {height: 175, marginTop: 23, justifyContent: 'flex-end', overflow: 'hidden'},
  heroImage: {borderRadius: 2},
  heroOverlay: {padding: 18, paddingTop: 55, backgroundColor: 'rgba(4,9,13,.38)'},
  heroEyebrow: {color: colors.red, fontSize: 8, fontWeight: '800', letterSpacing: 1.6},
  heroTitle: {color: colors.white, fontSize: 24, lineHeight: 27, fontWeight: '700', marginTop: 6},
  formCard: {backgroundColor: colors.panel, padding: 18, marginTop: 14, borderWidth: 1, borderColor: colors.border},
  fieldWrap: {gap: 8},
  fieldLabel: {color: '#B9C2C8', fontSize: 8, fontWeight: '800', letterSpacing: 1.5},
  textField: {height: 48, paddingHorizontal: 14, color: colors.white, fontSize: 14, backgroundColor: colors.backgroundDeep, borderWidth: 1, borderColor: colors.border},
  selectField: {height: 48, paddingHorizontal: 13, backgroundColor: colors.backgroundDeep, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  selectValue: {color: colors.white, fontSize: 13, flex: 1},
  selectPlaceholder: {color: colors.muted, fontSize: 13, flex: 1},
  chevron: {color: colors.red, fontSize: 20, marginTop: -5},
  fieldRow: {flexDirection: 'row', gap: 12, marginTop: 16},
  fieldHalf: {flex: 1},
  sectionLabel: {color: colors.white, fontSize: 11, fontWeight: '800', letterSpacing: 1.4, marginTop: 28, marginBottom: 12},
  quickRow: {flexDirection: 'row', gap: 12},
  quickCard: {flex: 1, minHeight: 145, padding: 16, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border},
  quickIcon: {color: colors.red, fontSize: 25},
  quickTitle: {color: colors.white, fontSize: 16, fontWeight: '700', marginTop: 12},
  quickText: {color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 5},
  contentScroll: {paddingHorizontal: 20, paddingBottom: 35},
  pageEyebrow: {color: colors.red, fontSize: 9, fontWeight: '800', letterSpacing: 1.8, marginTop: 20},
  pageTitle: {color: colors.white, fontSize: 34, lineHeight: 38, fontWeight: '700', letterSpacing: -1.2, marginTop: 8},
  pageLead: {color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 10},
  chips: {gap: 8, paddingVertical: 22, paddingRight: 20},
  chip: {height: 34, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 15, alignItems: 'center', justifyContent: 'center'},
  chipActive: {backgroundColor: colors.red, borderColor: colors.red},
  chipText: {color: colors.muted, fontSize: 9, fontWeight: '800', letterSpacing: 1},
  chipTextActive: {color: colors.white},
  cardList: {gap: 16},
  contentCard: {backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, overflow: 'hidden'},
  cardImage: {width: 300, maxWidth: '100%', alignSelf: 'center', aspectRatio: 300 / 165, resizeMode: 'cover'},
  cardCopy: {padding: 16},
  cardTopLine: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  cardCategory: {color: colors.red, fontSize: 8, fontWeight: '800', letterSpacing: 1.4},
  cardMeta: {color: '#D7DCDF', fontSize: 10, fontWeight: '600'},
  cardTitle: {color: colors.white, fontSize: 20, fontWeight: '700', marginTop: 8},
  cardDescription: {color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 7},
  cardLinkRow: {marginTop: 15, paddingTop: 13, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: 'row', justifyContent: 'space-between'},
  cardLink: {color: colors.white, fontSize: 9, fontWeight: '800', letterSpacing: 1.2},
  modalBackdrop: {flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end'},
  optionSheet: {backgroundColor: colors.panel, paddingHorizontal: 22, paddingBottom: 30, borderTopWidth: 1, borderColor: colors.border},
  sheetHandle: {alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#54616A', marginTop: 10, marginBottom: 22},
  modalTitle: {color: colors.white, fontSize: 22, fontWeight: '700', marginBottom: 12},
  optionList: {maxHeight: 420},
  optionRow: {minHeight: 50, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  optionText: {color: '#D1D7DB', fontSize: 14},
  optionTextActive: {color: colors.white, fontWeight: '700'},
  radio: {width: 18, height: 18, borderRadius: 9, borderWidth: 1, borderColor: '#64717A', alignItems: 'center', justifyContent: 'center'},
  radioActive: {borderColor: colors.red},
  radioDot: {width: 8, height: 8, borderRadius: 4, backgroundColor: colors.red},
  detailModal: {flex: 1, backgroundColor: colors.background},
  closeButton: {position: 'absolute', zIndex: 2, top: Platform.OS === 'ios' ? 48 : 14 + (StatusBar.currentHeight ?? 0), right: 16, width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white, shadowColor: '#000000', shadowOpacity: 0.28, shadowRadius: 8, shadowOffset: {width: 0, height: 3}, elevation: 6},
  closeButtonText: {color: '#000000', fontSize: 29, lineHeight: 31},
  detailScroll: {paddingBottom: 35},
  detailImage: {height: 300, alignSelf: 'center', resizeMode: 'cover'},
  detailCategory: {color: colors.red, fontSize: 9, fontWeight: '800', letterSpacing: 1.8, marginTop: 44, marginHorizontal: 22},
  detailTitle: {color: colors.white, fontSize: 34, lineHeight: 39, fontWeight: '700', letterSpacing: -1, marginTop: 8, marginHorizontal: 22},
  detailMeta: {color: '#D7DCDF', fontSize: 13, fontWeight: '700', marginTop: 9, marginHorizontal: 22},
  detailRule: {height: 1, backgroundColor: colors.border, marginVertical: 22, marginHorizontal: 22},
  detailDescription: {color: '#B5BEC4', fontSize: 14, lineHeight: 22, marginBottom: 14, marginHorizontal: 22},
  confirmCard: {margin: 22, padding: 24, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border, alignItems: 'center'},
  confirmIcon: {width: 54, height: 54, borderRadius: 27, backgroundColor: 'rgba(255,36,56,.14)', alignItems: 'center', justifyContent: 'center'},
  confirmIconText: {color: colors.red, fontSize: 25, fontWeight: '700'},
  confirmTitle: {color: colors.white, fontSize: 24, fontWeight: '700', marginTop: 18, textAlign: 'center'},
  confirmText: {color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 10, textAlign: 'center'},
  controlScroll: {paddingBottom: 30},
  controlHeader: {paddingHorizontal: 24, paddingTop: 27, paddingBottom: 21, borderBottomWidth: 1, borderBottomColor: colors.border},
  controlTitle: {color: colors.white, fontSize: 23, lineHeight: 28, fontWeight: '800', letterSpacing: -0.6},
  controlKicker: {color: colors.red, fontSize: 9, lineHeight: 12, fontWeight: '800', letterSpacing: 2, marginTop: 6},
  controlLabel: {color: '#74818B', fontSize: 9, lineHeight: 12, fontWeight: '800', letterSpacing: 2},
  controlMuted: {color: colors.muted, fontSize: 12, fontWeight: '600'},
  currentTemperature: {height: 167, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1, borderBottomColor: colors.border},
  temperatureRow: {flexDirection: 'row', alignItems: 'flex-start', marginTop: 15},
  currentTemperatureValue: {color: colors.white, fontSize: 80, lineHeight: 82, fontWeight: '800', letterSpacing: -3},
  temperatureUnit: {color: '#A6AFB5', fontSize: 28, lineHeight: 38, fontWeight: '800', marginLeft: 5},
  controlSection: {paddingHorizontal: 24, paddingVertical: 24, borderBottomWidth: 1, borderBottomColor: colors.border},
  temperatureLimits: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 17},
  temperatureControl: {height: 65, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 32},
  temperatureButton: {width: 42, height: 42, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center'},
  temperatureButtonText: {color: colors.muted, fontSize: 27, lineHeight: 30},
  setTemperatureValue: {minWidth: 100, color: '#F20B18', fontSize: 35, lineHeight: 42, fontWeight: '800', textAlign: 'center'},
  segmentRow: {flexDirection: 'row', gap: 8, marginTop: 15},
  segmentButton: {flex: 1, height: 42, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center'},
  segmentButtonActive: {backgroundColor: '#EA0711', borderColor: '#EA0711'},
  segmentButtonSelected: {backgroundColor: '#34414C', borderColor: '#34414C'},
  segmentText: {color: colors.muted, fontSize: 9, fontWeight: '800'},
  segmentTextActive: {color: colors.white},
  controlInput: {height: 47, marginTop: 9, paddingHorizontal: 16, backgroundColor: colors.panelSoft, color: colors.white, fontSize: 13},
  controlInputDisabled: {opacity: 0.45},
  controlSelect: {height: 47, marginTop: 9, paddingHorizontal: 16, backgroundColor: colors.panelSoft, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  controlSelectValue: {color: colors.white, fontSize: 13, fontWeight: '600'},
  controlSelectPlaceholder: {color: colors.muted, fontSize: 13},
  controlSelectArrow: {color: colors.red, fontSize: 20, lineHeight: 22, marginTop: -5},
  locationSelect: {minHeight: 62, marginTop: 9, paddingHorizontal: 16, paddingVertical: 11, backgroundColor: colors.panelSoft, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  locationSelectCopy: {flex: 1, paddingRight: 12},
  locationAddress: {color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 3},
  taxiPickupLabel: {color: '#B9C2C8', fontSize: 8, fontWeight: '800', letterSpacing: 1.5, marginTop: 18},
  taxiDestinationLabel: {color: '#B9C2C8', fontSize: 8, fontWeight: '800', letterSpacing: 1.5, marginTop: 18},
  routeCard: {marginHorizontal: 24, marginVertical: 18, padding: 18, backgroundColor: colors.panel, borderWidth: 1, borderColor: colors.border},
  routeStop: {flexDirection: 'row', alignItems: 'center', marginTop: 17},
  routeStartDot: {width: 13, height: 13, borderRadius: 7, borderWidth: 3, borderColor: colors.red, backgroundColor: colors.panel},
  routeEndDot: {width: 13, height: 13, borderRadius: 2, backgroundColor: colors.red},
  routeLine: {width: 1, height: 25, marginLeft: 6, marginTop: 2, marginBottom: -14, backgroundColor: '#52616C'},
  routeStopCopy: {flex: 1, marginLeft: 12},
  routeStopName: {color: colors.white, fontSize: 13, fontWeight: '700'},
  routeSummary: {minHeight: 43, marginTop: 20, paddingTop: 14, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: 'row', alignItems: 'center'},
  routeSummaryText: {color: '#C9D0D5', fontSize: 11, fontWeight: '700'},
  routeSummarySeparator: {color: colors.muted, fontSize: 12, marginHorizontal: 7},
  routePrice: {color: colors.red, fontSize: 15, fontWeight: '800', marginLeft: 'auto'},
  controlActionSection: {paddingHorizontal: 24, paddingTop: 22, paddingBottom: 28},
  controlActionButton: {height: 54, backgroundColor: '#EA0711', alignItems: 'center', justifyContent: 'center'},
  controlActionButtonDisabled: {backgroundColor: '#34414C'},
  controlActionText: {color: colors.white, fontSize: 13, fontWeight: '800', letterSpacing: 2.5},
  taxiHint: {color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 11},
  estimateSection: {flexDirection: 'row', gap: 12, paddingHorizontal: 24, paddingVertical: 22, borderBottomWidth: 1, borderBottomColor: colors.border},
  estimateCard: {flex: 1, height: 104, borderWidth: 1, borderColor: colors.border, padding: 16, justifyContent: 'space-between'},
  estimateValue: {color: colors.white, fontSize: 29, lineHeight: 35, fontWeight: '800'},
  priceRow: {flexDirection: 'row', alignItems: 'baseline'},
  priceValue: {color: '#F20B18', fontSize: 22, lineHeight: 28, fontWeight: '800'},
  taxiDateSection: {paddingHorizontal: 24, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: colors.border},
  tabSafe: {backgroundColor: colors.backgroundDeep},
  tabBar: {height: 64, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.backgroundDeep, flexDirection: 'row', alignItems: 'center'},
  tabItem: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3},
  tabIcon: {color: '#6F7B84', fontSize: 19, fontWeight: '600'},
  tabLabel: {color: '#6F7B84', fontSize: 9, fontWeight: '700'},
  tabActive: {color: colors.red},
});
